"""empty message

Revision ID: 3e5556e952bf
Revises: 99d29e3ba3ac
Create Date: 2025-06-08 13:04:04.642644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5556e952bf'
down_revision = '99d29e3ba3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
